#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Create background mesh
runApplication blockMesh

# Optional: select cells around the stent and refine them
runApplication -s 1 topoSet -dict system/topoSetDict.1
runApplication -s 1 refineMesh -dict system/refineMeshDict -overwrite
runApplication -s 2 topoSet -dict system/topoSetDict.2
runApplication -s 2 refineMesh -dict system/refineMeshDict -overwrite

# Run in serial
#runApplication pisoHFDIBFoam

# Run in parallel
runApplication decomposePar
runParallel pimpleHFDIBFoam
runApplication reconstructPar

# ----------------------------------------------------------------- end-of-file
